version: 1.0.{build}-{branch}
os: Windows Server 2012 R2

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install --path .bundle

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test


notifications:
  - provider: Slack
    incoming_webhook:
      secure: oYviEmkGtgAO8Ij90h3s60tvql2KDBmHGkL7YHb1HAdd2hlEHsC36Xkew7Ei01nUsI7ZfcvbbjDCu+lImrHOpl4Jcmvd5lsZL9k1bhxup7Q=
    channel: general
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false